### ISSUE TITLE
Handle calls to applyDynamicNamed where only some parameters are named

### ISSUE THREAD

**Issue by shadaj** [shadaj/scalapy#10]
This is a very common pattern especially with TensorFlow. Right now, ScalaPy ends up generating code like `foo( = param1, = param2, named = param3)` instead of just directly passing the unnamed parameters in.

**Comment by bfdes** [comment]
I was thinking of attempting this ticket. Here are my findings: 

Scala does not allow two sets of named arguments, so we cannot have a signature like `applyDynamic(method: String)(kwargs: (String, Any)*, args: Any*)`. But we can treat positional arguments as key-value arguments where the key has no length. So my proposed solution is to use `applyDynamic(method: String)(args: (String, Any)*)` in the general case.

Another note: I think the responsibility of raising an error when a kwarg precedes an arg falls on the Python interpreter. It can be done on this side though. 

Where would be the best place to test the generated code? I added a few cases to `MethodCallingTest` but they seem to be passing unexpectedly.
