### ISSUE TITLE
cannot load libpython3.so

### ISSUE THREAD

**Issue by k2d2o2** [shadaj/scalapy#121]
I first tried scalapy following the instructions on the website (with 4.0.0) and the example shows next error

![image](https://user-images.githubusercontent.com/3773688/99161852-da0f7f80-2739-11eb-9984-06ac0d5e2cbe.png)

```
$ python3-config --ldflags
-L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -L/usr/lib  -lcrypt -lpthread -ldl  -lutil -lm -lm 
```

**Comment by shadaj** [comment]
Which files are visible inside `/usr/lib/python3.8/config-3.8-x86_64-linux-gnu`? On some systems only `python3.xm.so` is available. There's a fix to search for this in master, but it didn't make it into the 0.4.0 release.

**Comment by shadaj** [comment]
Also, the fact that the exception showed up is a bit odd, it seems like the JNA exception isn't getting caught by the `Try` wrapper. I'll investigate this a bit more.

**Comment by k2d2o2** [comment]
> usr/lib/python3.8/config-3.8-x86_64-linux-gnu
Thank you for fast reply. 
Here is the list of files. I'm using Ubuntu-20.04
```
 $ ls /usr/lib/python3.8/config-3.8-x86_64-linux-gnu
Makefile  Setup  Setup.local  config.c  config.c.in  install-sh  libpython3.8-pic.a  libpython3.8.a  libpython3.8.so  makesetup  python-config.py  python.o
```

**Comment by shadaj** [comment]
@k2d2o2 ah, yeah ScalaPy doesn't currently include Python 3.8 in its default search list, though it probably should. For now, you can add the environment variable `SCALAPY_PYTHON_LIBRARY=python3.8` before launching SBT to let ScalaPy know to use that specific version.

**Comment by dokang89** [comment]
Oh Thanks that works!

**Comment by k2d2o2** [comment]
Thanks, that works!
