### ISSUE TITLE
JNA library loading fallback doesn't work

### ISSUE THREAD

**Issue by bbstilson** [shadaj/scalapy#125]
We chatted briefly in gitter, but I think this might be a better medium. I created a repo to hopefully help debugging the issue. 

https://github.com/bbstilson/scalapy-test

**Comment by shadaj** [comment]
Thanks for the repro @bbstilson! I'll take a look shortly

**Comment by shadaj** [comment]
So looks like `python3-config --prefix` is broken, but `python3-config --configdir` gives us the right directory. Could you try using that for the JNA library path instead? If it works I'll update the docs to use that instead.

**Comment by lasimon** [comment]
In my case that now gives the right directory but I still get the same message saying it can't find libpython3.so.  Maybe scalapy is blowing up trying to use libpython3.so when it isn't present rather than going on to use the libpython3.7.so I do have in the directory?

**Comment by bbstilson** [comment]
Hey @shadaj , I pushed your suggestion to the repo. Still the same problem unfortunately:

```
[error] Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'python3':
[error] libpython3.so: cannot open shared object file: No such file or directory
[error] libpython3.so: cannot open shared object file: No such file or directory
```

**Comment by shadaj** [comment]
@lasimon that indeed seems to be the bug. My guess is that Scala's `Try` isn't catching the JNA load failure. Unfortunately, I'm a bit bogged down by midterms and PhD applications this week, but I'll definitely try to get to it next week!

In the meantime, could you try setting the environment variable `SCALAPY_PYTHON_LIBRARY` to `python3.7`? That is always loaded first if it's available.

**Comment by PeterAJansen** [comment]
I had the same (or, a similar) issue.  I think it was also complicated by using anaconda environments.  Here's my hacky fix:

Step 1: Locate the environment
```
find ~ -name libpython3*.so -ls
...
48798033      0 lrwxrwxrwx   1 peter    peter          20 Oct  2 00:18 /home/peter/anaconda3/envs/scigridworld/lib/libpython3.7m.so -> libpython3.7m.so.1.0
 48794360     16 -rwxrwxr-x   4 peter    peter       15616 Aug 31 05:50 /home/peter/anaconda3/envs/scigridworld/lib/libpython3.so
 5
...
```

Step 2: Plug that manually into the build.sbt file: 
```
name := "science-gridworld-scala"

version := "1.0"

scalaVersion := "2.12.9"

// ScalaPy
libraryDependencies += "me.shadaj" %% "scalapy-core" % "0.4.0"

fork := true

import scala.sys.process._
javaOptions += s"-Djna.library.path=/home/peter/anaconda3/envs/scigridworld/lib/"
```

Then the magic seems to happen:
```
package gridworld.entrypoints

import me.shadaj.scalapy.py
import me.shadaj.scalapy.py.SeqConverters

object EntryPoint {

  def pythonTest(): Unit = {
    println ("Python Test: ")
    val listLengthPython = py.Dynamic.global.len(List(1, 2, 3).toPythonProxy)
    val listLength = listLengthPython.as[Int]

    println(listLengthPython)
    println(listLength)
  }

  def main(args:Array[String]): Unit = {
    pythonTest()
  }

}

```

Output:
```
sbt run
[info] TestPython Test: 
[info] 3
[info] 3
[success] Total time: 1 s, completed Dec 14, 2020 11:53:30 AM
```
