### ISSUE TITLE
Add python 3.8 and 3.9 support

### ISSUE THREAD

**Issue by shilkazx** [shadaj/scalapy#136]
Please add python3.8 and 3.9 support in future version. IMHO a minor modification of CPythonAPI.scala is enough.

**Comment by shadaj** [comment]
I'm definitely planning to do this soon! Hoping to switch to GitHub actions, which will allow us to have a much wider matrix so that we can test support with all these Python versions.

**Comment by shilkazx** [comment]
> I'm definitely planning to do this soon! Hoping to switch to GitHub actions, which will allow us to have a much wider matrix so that we can test support with all these Python versions.

Great job! Waiting for the update.

**Comment by shilkazx** [comment]
I've try to compile a modified version(change "3.7" to "3.9" in CPythonAPI.scala) for python 3.9 but I failed. It's weird that the modified version can not locate python library.
Btw, both test environment are based on conda-env management, the only different is python version.

**Comment by shilkazx** [comment]
Update:
Under correct setting of SCALAPY_PYTHON_LIBRARY and LD_LIBRARY_PATH, python3.8 works properly, but python3.9 still malfunction.

**Comment by shadaj** [comment]
https://github.com/shadaj/scalapy/pull/139 :) there's indeed a breaking API change in Python 3.9 that crashes ScalaPy, but I'm working on fixing it right now!
