### ISSUE TITLE
Slow transform from Python Seq to Scala Seq

### ISSUE THREAD

**Issue by razem-io** [shadaj/scalapy#158]
I am trying to use scalapy to convert vision data from a python lib [pypylon](https://github.com/basler/pypylon) to a scala collection. To transfer a 2444x2048 matrix of pixels to scala it almost takes 10 seconds.

Is there a way to speed up the process significantly? I have already seen this https://github.com/shadaj/scalapy/pull/30 but wanted to ask, if there is a workaround for this performance issue.

**Comment by shadaj** [comment]
@razem-io thanks for raising this issue, this is definitely an important use case that should be handled better. Right now, there's unfortunately not too many good workarounds other than use Scala Native (which will eliminate most of the overhead) or defer loading data into Scala by using Python APIs to process the data instead.

I think the best solution to improving performance on the JVM would be have specialized reader-writer implementations for Java arrays of primitives, which can be read from [quite efficiently](http://www.iitk.ac.in/esc101/05Aug/tutorial/native1.1/implementing/array.html). Then, we would need some custom C code for each type of primitive array that transfer the elements to/from a Python sequence.

**Comment by razem-io** [comment]
@shadaj thank you for the quick detailed response. I think I got most of it.  I think scala native is currently not an option, as the code base I am working on does use alot of scala libraries not yet ported to scala native. 
The second option sounds very interesting and would be a nice addition to this library. Maybe I find the time to look into it. Thank you very much!
