### ISSUE TITLE
py.module can't load .so file in format xxx.xxx.so

### ISSUE THREAD

**Issue by dev590t** [shadaj/scalapy#161]
## Description
I'm trying to run scalapy with anaconda. 
Scalapy isn't able to load .so file in format xxx.xxx.so. It can only load so file in format xxx.so
## Example
.so file directory:
```
$ ls /home/kadf/usr/anaconda3/envs/tiktok/lib/python3.7/
_queue.cpython-37m-x86_64-linux-gnu.so
_crypt.cpython-37m-x86_64-linux-gnu.so 
_crypt.so 
```
configuration:
```
    "-Djava.library.path=/home/kadf/usr/anaconda3/envs/tiktok/lib/python3.7/lib-dynload",
    "-Djna.library.path=/home/kadf/usr/anaconda3/envs/tiktok/lib/python3.7/lib-dynload"
```
run code in console:
```
 kadf-test@ py.module("sys").path = py"['/home/kadf/usr/anaconda3/envs/tiktok/lib/python3.7/lib-dynload']"  

 kadf-test@ py.module("_queue")  
 me.shadaj.scalapy.py.PythonException: <class 'ModuleNotFoundError'> No module named '_queue'
// because _queue.cpython-37m-x86_64-linux-gnu.so in xxx.xxx.so format
   
 kadf-test@ py.module("_crypt") 
 res6: py.Module = <module '_crypt' from '/home/kadf/usr/anaconda3/envs/tiktok/lib/python3.7/lib-dynload/_crypt.so'>
// because _crypt.so  in xxx.so format
```
## Additional information
I'm trying reproduce the issue in raw python interpreter.
py.module use python 's `__import__` to load module when I check the [code](https://github.com/shadaj/scalapy/blob/3ff26c91cc3d9bdc438a4eea90fecb5ff601fd00/core/shared/src/main/scala/me/shadaj/scalapy/py/package.scala#L11) the  [documentation](https://docs.python.org/3/c-api/import.html), so:
```
rm _crypt.so
ls /home/kadf/usr/anaconda3/envs/tiktok/lib/python3.7/
_crypt.cpython-37m-x86_64-linux-gnu.so 
$ ipython
...
In [2]: sys.path = ['/home/kadf/usr/anaconda3/envs/tiktok/lib/python3.7/lib-dynload']
In [4]: sys.modules.get('_crypt') ## verify module no loaded
In [5]: __import__('_crypt')
   ...: 
Out[5]: <module '_crypt' from '/home/kadf/usr/anaconda3/envs/tiktok/lib/python3.7/lib-dynload/_crypt.cpython-37m-x86_64-linux-gnu.so'>
```
However `__import__` can solve xxx.xxx.so file

**Comment by shadaj** [comment]
@zhenleibb hmm, that's surprising, ScalaPy doesn't interfere with Python's loading mechanisms at all so it's not immediately clear to my why this behavior would be different. The one thing I notice is that the `_crypt` library is fr `python-37m`, with an `m` at the end that might be mismatched with the Python library being loaded by ScalaPy (`3.7` takes precedence over `3.7m` when loading). Could you try setting the environment variable `SCALAPY_PYTHON_LIBRARY=python3.7m` to override ScalaPy's Python search mechanism?

**Comment by zhenleibb** [comment]
@shadaj 
> Could you try setting the environment variable SCALAPY_PYTHON_LIBRARY=python3.7m to override ScalaPy's Python search mechanism?

It doesn't work :confused:

**Comment by zhenleibb** [comment]
However I remark a point.

Scalapy can solve the name if the path is initialy present in sys.path
```
 (base) 1406 $ mill -i tiktok.repl
...
kadf-test@ py.module("sys").path 
res2: py.Dynamic = ['/usr/lib/python3.8/lib-dynload', ..]

kadf-test@ py.module("_queue")  
res3: py.Module = <module '_queue' from '/usr/lib/python3.8/lib-dynload/_queue.cpython-38-x86_64-linux-gnu.so'>

kadf-test@ py.module("sys").executable 
res4: py.Dynamic = /home/kadf/usr/anaconda3/bin/python3
```

But if I add manually the path, it can't solve the name:
```
(base) 1409 $ PYTHONPATH=/home/kadf/usr/anaconda3/envs/tiktok/lib/python3.7/lib-dynload mill -i tiktok.repl
..
kadf-test@ py.module("sys").path 
res2: py.Dynamic = ['/home/kadf/usr/anaconda3/envs/tiktok/lib/python3.7/lib-dynload',  '/usr/lib/python3.8/lib-dynload', ..]

// I try to solve _queue in path home/kadf/usr/anaconda3/envs/tiktok/lib/python3.7/lib-dynload that I have manually add 
kadf-test@ py.module("sys").path = py"['/home/kadf/usr/anaconda3/envs/tiktok/lib/python3.7/lib-dynload']"  


kadf-test@ py.module("_queue")  
me.shadaj.scalapy.py.PythonException: <class 'ModuleNotFoundError'> No module named '_queue'
 
kadf-test@ py.module("sys").executable 
res4: py.Dynamic = /home/kadf/usr/anaconda3/bin/python3
```
The difference is that `/usr/lib/python3.8/lib-dynload` is [CPythonAPI.Py_Initialize()](https://github.com/shadaj/scalapy/blob/0b38d0bf4eee4bacae92e5a29a3423fad7576038/core/shared/src/main/scala/me/shadaj/scalapy/interpreter/CPythonInterpreter.scala#L9) that add it(I think). Its [documentation](https://docs.python.org/3/c-api/init.html#c.Py_Initialize) says:
> This initializes the table of loaded modules (sys.modules), and creates the fundamental modules builtins, __main__ and sys. It also initializes the module search path (sys.path).
