### ISSUE TITLE
How to instantiate a Python Class ?

### ISSUE THREAD

**Issue by sgsaikat** [shadaj/scalapy#204]
I was wondering if it's possible to instantiate Python Classes through ScalaPy.
For example, let's say I would like to instantiate the `collections.Counter` Class.
`val collections = py.module("collections")
  val counter = new collections.Counter()`
This code throws up the error - `trait Dynamic is abstract; cannot be instantiated`

Is this possible ? If yes, can someone please share a sample code to use a `Counter` object in the script ?

Thanks!

**Comment by shadaj** [comment]
Just like in Python, you can construct values without the `new` keyword, so you can do `val counter = collections.Counter()`!
