### ISSUE TITLE
"lib/" folder

### ISSUE THREAD

**Issue by paul-reiners** [shadaj/scalapy#3]
This instructions mention a "lib/" folder:

> First, build Jep and place your jep.so and libjep.jnilib files in the lib/ folder (you will probably have to create this) for SBT to pick them up. 

Where **exactly** does this "lib/" folder go?  At the top-most directory?  At the user's home directory?  In a project directory?

**Comment by shadaj** [comment]
It must go in the project directory (the one containing `build.sbt`). Alternatively, you can skip copying the files and point the JVM to the location of the `jep` Python package, something like `/usr/local/lib/python3.6/site-packages/jep`.
