### ISSUE TITLE
Is scalapy working with scala-native?

### ISSUE THREAD

**Issue by davips** [shadaj/scalapy#31]
I created a default scala-native project and included scalapy dependence as below. But I couldn't manage to make it work.

plugins.sbt:

    addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.3.9")

build.sbt:
```scala
    scalaVersion := "2.11.12"

    nativeLinkStubs := true

    enablePlugins(ScalaNativePlugin)

    libraryDependencies += "me.shadaj" % "scalapy-core_native0.3_2.11" % "0.3.0+1-e1acbe6f"
```

Main.scala:

```scala
    import me.shadaj.scalapy.py
    object Main extends App {
        println("Hello, world!")
        val listLengthPython = py.global.len(List(1, 2, 3))
        val listLength = listLengthPython.as[Int]
    }
```

build.properties:

```scala
    sbt.version = 1.2.6
```
Gives several errors like this first:

    [error] /home/user/hello/target/scala-2.11/native/me.shadaj.scalapy.py.ll.o: In function `me.shadaj.scalapy.py.CPyValue::cleanup_unit':
    [error] me.shadaj.scalapy.py.ll:(.text+0x51d): undefined reference to `Py_DecRef'

**Comment by shadaj** [comment]
Hi @davips!

To run ScalaPy with Scala Native, you'll also need to link against the native Python libraries. You can do this by adding an additional SBT setting:
```scala
nativeLinkingOptions ++= {
  import scala.sys.process._
  "python3-config --ldflags".!!.split(' ').map(_.trim).filter(_.nonEmpty).toSeq
}
```

Just realized that this wasn't included in the docs, so I'll leave this issue open as a reminder to document this setting.

**Comment by davips** [comment]
Thanks, works fine now!

**Comment by shadaj** [comment]
Resolved as part of the new docs site
