### ISSUE TITLE
Fail to install ScalaPy

### ISSUE THREAD

**Issue by SaintNazaire** [shadaj/scalapy#4]
## **Attempted (failed) approaches**

- **Approach 1**: added libraryDependencies += "me.shadaj" %% "scalapy" % "0.1.0-SNAPSHOT" to the build.sbt file of a project
- **Approach 2**: downloaded github's content to the projects' lib directory of a project
- **Approach 3**: downloaded github's to a standlone scalapy only project and attempted to build

## **System information**

- Windows 10 professional
- Scala 2.12.3 (built-in), 2.10.6 (built-in), 2.11.11 (built-in)
- sbt 1.1.2 (local 0.13.13 as per scalapy's build.sbt specs)
- Java 1.8 JRE 1.8.0_171
- Java 8 JDK 171
- Python 3.6.4 (Conda 4.4.10, Anaconda 1.6.9 64x bits)
- jep 3.7.1
- Eclispe Oxygen.3a (4.7.3a) build 20180405-1200
- PyDev 6.3.3.201805051638

## **Command triggering issue & relevant error log**

**Approach 1**

`sbt eclipse`

> [info] Loading settings from plugins.sbt ...
> [info] Loading project definition from C:\Users\XXXX\scala_test\project
> [info] Loading settings from build.sbt ...
> [info] Set current project to scala_test (in build file:/C:/Users/XXXX/scala_test/)
> [info] About to create Eclipse project files for your project(s).
> [info] Updating ...
> [warn] 	module not found: me.shadaj#scalapy_2.12;0.1.0-SNAPSHOT
> [warn] ==== local: tried
> [warn]   C:\Users\XXXX\.ivy2\local\me.shadaj\scalapy_2.12\0.1.0-SNAPSHOT\ivys\ivy.xml
> [warn] ==== public: tried
> [warn]   https://repo1.maven.org/maven2/me/shadaj/scalapy_2.12/0.1.0-SNAPSHOT/scalapy_2.12-0.1.0-SNAPSHOT.pom
> [warn] ==== local-preloaded-ivy: tried
> [warn]   C:\Users\XXXX.sbt\preloaded\me.shadaj\scalapy_2.12\0.1.0-SNAPSHOT\ivys\ivy.xml
> [warn] ==== local-preloaded: tried
> [warn]   file:/C:/Users/XXXX/.sbt/preloaded/me/shadaj/scalapy_2.12/0.1.0-SNAPSHOT/scalapy_2.12-0.1.0-SNAPSHOT.pom
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 	::          UNRESOLVED DEPENDENCIES         ::
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 	:: me.shadaj#scalapy_2.12;0.1.0-SNAPSHOT: not found
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 
> [warn] 	Note: Unresolved dependencies path:
> [warn] 		me.shadaj:scalapy_2.12:0.1.0-SNAPSHOT (C:\Users\XXXX\scala_test\build.sbt#L1-2)
> [warn] 		  +- default:scala_test_2.12:0.1.0-SNAPSHOT
> [error] sbt.librarymanagement.ResolveException: unresolved dependency: me.shadaj#scalapy_2.12;0.1.0-SNAPSHOT: not found
> [error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
> [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
> [error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
> [error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
> [error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
> [error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
> [error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
> [error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
> [error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
> [error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
> [error] 	at xsbt.boot.Using$.apply(Using.scala:9)
> [error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
> [error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
> [error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
> [error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
> [error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
> [error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
> [error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
> [error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
> [error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
> [error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
> [error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
> [error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
> [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
> [error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
> [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
> [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
> [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
> [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
> [error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
> [error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
> [error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2386)
> [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
> [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
> [error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
> [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
> [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
> [error] 	at sbt.Execute.work(Execute.scala:271)
> [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
> [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
> [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [error] 	at java.lang.Thread.run(Thread.java:748)
> [error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: me.shadaj#scalapy_2.12;0.1.0-SNAPSHOT: not found
> [info] Updating ...
> [warn] 	module not found: me.shadaj#scalapy_2.12;0.1.0-SNAPSHOT
> [warn] ==== local: tried
> [warn]   C:\Users\XXXX\.ivy2\local\me.shadaj\scalapy_2.12\0.1.0-SNAPSHOT\ivys\ivy.xml
> [warn] ==== public: tried
> [warn]   https://repo1.maven.org/maven2/me/shadaj/scalapy_2.12/0.1.0-SNAPSHOT/scalapy_2.12-0.1.0-SNAPSHOT.pom
> [warn] ==== local-preloaded-ivy: tried
> [warn]   C:\Users\XXXX\.sbt\preloaded\me.shadaj\scalapy_2.12\0.1.0-SNAPSHOT\ivys\ivy.xml
> [warn] ==== local-preloaded: tried
> [warn]   file:/C:/Users/XXXX/.sbt/preloaded/me/shadaj/scalapy_2.12/0.1.0-SNAPSHOT/scalapy_2.12-0.1.0-SNAPSHOT.pom
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 	::          UNRESOLVED DEPENDENCIES         ::
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 	:: me.shadaj#scalapy_2.12;0.1.0-SNAPSHOT: not found
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 
> [warn] 	Note: Unresolved dependencies path:
> [warn] 		me.shadaj:scalapy_2.12:0.1.0-SNAPSHOT (C:\Users\XXXX\scala_test\build.sbt#L1-2)
> [warn] 		  +- default:scala_test_2.12:0.1.0-SNAPSHOT
> [error] sbt.librarymanagement.ResolveException: unresolved dependency: me.shadaj#scalapy_2.12;0.1.0-SNAPSHOT: not found
> [error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
> [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
> [error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
> [error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
> [error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
> [error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
> [error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
> [error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
> [error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
> [error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
> [error] 	at xsbt.boot.Using$.apply(Using.scala:9)
> [error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
> [error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
> [error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
> [error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
> [error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
> [error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
> [error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
> [error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
> [error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
> [error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
> [error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
> [error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
> [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
> [error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
> [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
> [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
> [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
> [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
> [error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
> [error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
> [error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2386)
> [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
> [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
> [error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
> [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
> [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
> [error] 	at sbt.Execute.work(Execute.scala:271)
> [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
> [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
> [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [error] 	at java.lang.Thread.run(Thread.java:748)
> [error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: me.shadaj#scalapy_2.12;0.1.0-SNAPSHOT: not found
> [info] Updating ...
> [warn] 	module not found: me.shadaj#scalapy_2.12;0.1.0-SNAPSHOT
> [warn] ==== local: tried
> [warn]   C:\Users\XXXX\.ivy2\local\me.shadaj\scalapy_2.12\0.1.0-SNAPSHOT\ivys\ivy.xml
> [warn] ==== public: tried
> [warn]   https://repo1.maven.org/maven2/me/shadaj/scalapy_2.12/0.1.0-SNAPSHOT/scalapy_2.12-0.1.0-SNAPSHOT.pom
> [warn] ==== local-preloaded-ivy: tried
> [warn]   C:\Users\XXXX\.sbt\preloaded\me.shadaj\scalapy_2.12\0.1.0-SNAPSHOT\ivys\ivy.xml
> [warn] ==== local-preloaded: tried
> [warn]   file:/C:/Users/XXXX/.sbt/preloaded/me/shadaj/scalapy_2.12/0.1.0-SNAPSHOT/scalapy_2.12-0.1.0-SNAPSHOT.pom
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 	::          UNRESOLVED DEPENDENCIES         ::
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 	:: me.shadaj#scalapy_2.12;0.1.0-SNAPSHOT: not found
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 
> [warn] 	Note: Unresolved dependencies path:
> [warn] 		me.shadaj:scalapy_2.12:0.1.0-SNAPSHOT (C:\Users\XXXX\scala_test\build.sbt#L1-2)
> [warn] 		  +- default:scala_test_2.12:0.1.0-SNAPSHOT
> [error] sbt.librarymanagement.ResolveException: unresolved dependency: me.shadaj#scalapy_2.12;0.1.0-SNAPSHOT: not found
> [error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
> [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
> [error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
> [error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
> [error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
> [error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
> [error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
> [error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
> [error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
> [error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
> [error] 	at xsbt.boot.Using$.apply(Using.scala:9)
> [error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
> [error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
> [error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
> [error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
> [error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
> [error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
> [error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
> [error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
> [error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
> [error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
> [error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
> [error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
> [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
> [error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
> [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
> [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
> [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
> [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
> [error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
> [error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
> [error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2386)
> [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
> [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
> [error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
> [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
> [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
> [error] 	at sbt.Execute.work(Execute.scala:271)
> [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
> [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
> [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [error] 	at java.lang.Thread.run(Thread.java:748)
> [error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: me.shadaj#scalapy_2.12;0.1.0-SNAPSHOT: not found
> [info] Updating ...
> [warn] 	module not found: me.shadaj#scalapy_2.12;0.1.0-SNAPSHOT
> [warn] ==== local: tried
> [warn]   C:\Users\XXXX\.ivy2\local\me.shadaj\scalapy_2.12\0.1.0-SNAPSHOT\ivys\ivy.xml
> [warn] ==== public: tried
> [warn]   https://repo1.maven.org/maven2/me/shadaj/scalapy_2.12/0.1.0-SNAPSHOT/scalapy_2.12-0.1.0-SNAPSHOT.pom
> [warn] ==== local-preloaded-ivy: tried
> [warn]   C:\Users\XXXX\.sbt\preloaded\me.shadaj\scalapy_2.12\0.1.0-SNAPSHOT\ivys\ivy.xml
> [warn] ==== local-preloaded: tried
> [warn]   file:/C:/Users/XXXX/.sbt/preloaded/me/shadaj/scalapy_2.12/0.1.0-SNAPSHOT/scalapy_2.12-0.1.0-SNAPSHOT.pom
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 	::          UNRESOLVED DEPENDENCIES         ::
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 	:: me.shadaj#scalapy_2.12;0.1.0-SNAPSHOT: not found
> [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 
> [warn] 	Note: Unresolved dependencies path:
> [warn] 		me.shadaj:scalapy_2.12:0.1.0-SNAPSHOT (C:\Users\XXXX\scala_test\build.sbt#L1-2)
> [warn] 		  +- default:scala_test_2.12:0.1.0-SNAPSHOT
> [error] sbt.librarymanagement.ResolveException: unresolved dependency: me.shadaj#scalapy_2.12;0.1.0-SNAPSHOT: not found
> [error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
> [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
> [error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
> [error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
> [error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
> [error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
> [error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
> [error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
> [error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
> [error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
> [error] 	at xsbt.boot.Using$.apply(Using.scala:9)
> [error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
> [error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
> [error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
> [error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
> [error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
> [error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
> [error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
> [error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
> [error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
> [error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
> [error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
> [error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
> [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
> [error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
> [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
> [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
> [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
> [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
> [error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
> [error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
> [error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2386)
> [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
> [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
> [error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
> [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
> [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
> [error] 	at sbt.Execute.work(Execute.scala:271)
> [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
> [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
> [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [error] 	at java.lang.Thread.run(Thread.java:748)
> [error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: me.shadaj#scalapy_2.12;0.1.0-SNAPSHOT: not found
> [error] Could not create Eclipse project files:
> [error] [Error evaluating task 'scalacOptions': error,Error evaluating task 'externalDependencyClasspath': error,Error evaluating task 'update': error,Error evaluating task 'updateClassifiers': error,Error evaluating task 'updateClassifiers': error]

Then upon running in the Scala Interpreter

> <console>:12: error: not found: value me
>        me.shadaj
> 

**Approach 2**

No package me.shadaj exists

**Approach 3**

`sbt eclipse`

Errors (3 items)

> Archive for required library 'lib/jep.dll' in project 'scalapy' cannot be read or is not a valid ZIP file'

**This was fixed** by adding the jep-3.7.0.jar file to the Eclipse project's Java Build Path's Libraries in the Package Explorer.

> not found: type ObjectTupleReaders, Scala Problem
> not found: type ObjectTupleWriters, Scala Problem

Warning (1 item)

> abstract type T in type pattern me.shadaj.scalapy.py.NativeSeq[T] is unchecked since it is eliminated by erasure

**Comment by shadaj** [comment]
@SaintNazaire did you `publishLocal` ScalaPy before running your test project? It's not yet published to Maven Central yet.

**Comment by SaintNazaire** [comment]
@shadaj, no I didn't.
I assume I have to `publishTo := Some(Resolver.file("file",  new File( "path/to/my/maven-repo/releases" )) )`-something?
However could you beforehand tell me which approach to retain (1, 2, 3?)

**Comment by SaintNazaire** [comment]
@shadaj: w.o.n.d.e.r.f.u.l
