### ISSUE TITLE
Running tests now requires numpy installation

### ISSUE THREAD

**Issue by valencik** [shadaj/scalapy#41]
As of https://github.com/shadaj/scalapy/pull/29 running the unit tests now requires `numpy` to be installed.

The README currently doesn't mention this in the *Building* section.

@shadaj what do you think about keeping the unit tests "pure" to the standard distribution of python and perhaps having separate integration tests that use 3rd party modules?

**Comment by bfdes** [comment]
From #29, what constitutes “array like objects”? Can we test by passing a stub that implements this protocol? That way a numpy installation for test could become redundant.

**Comment by shadaj** [comment]
Yeah, I added the `numpy` test to make sure that we properly support other implementations that implement the sequence protocol but aren't regular Python lists. I think testing this behavior might work if we just index into a string instead.
