### ISSUE TITLE
JEP is still mentioned from getting-started.md

### ISSUE THREAD

**Issue by PawelLipski** [shadaj/scalapy#86]
Commit 3955cc18865433b01027b7ef7c3c888adec3ad2d (soon after v0.3.0 relese) removed the dependency on JEP, but there is still a couple places in the docs where JEP is referenced, as shown by `git grep -i jep`.

**Comment by shadaj** [comment]
I think all the current references to Jep are in the versioned docs, which are only updated when I tag a release. The 0.4.0 release is coming soon, have some very exciting improvements that I'm hoping to get into the release!

**Comment by SemanticBeeng** [comment]
@shadaj what are your plans for use of `jep` ?
I've used it before and plan to use in again but curious how this project plans to use it.

**Comment by shadaj** [comment]
@SemanticBeeng to enable tighter interop, especially with allowing Python code to access Scala collections, we ended up switching to directly binding to the Python native APIs rather than going through Jep.
