### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by fsauer65** [shadaj/scalapy#89]
(How) Can this be used with Python 2.7? Unfortunately, the python code I need to invoke from my scala project is 2.7 :-(
I've got it to work with JEP, but this seems to have a much nicer api.

Thanks,

**Comment by shadaj** [comment]
Unfortunately, given the EOL of Python 2 and the maintenance challenges in simultaneously supporting the native APIs of both Python 2 and Python 3, it's unlikely that ScalaPy will support Python 2 libraries. Perhaps something like `2to3` could be helpful in getting the 2.7 code converted to Python 3?
