### ISSUE TITLE
enable mutation of variable 

### ISSUE THREAD

**Issue by doofin** [shadaj/scalapy#9]
I tried this but not working 
```scala
  def mutateDynamicVar(value: Any) {
    println(s"mutateDynamicVar : $expr = $value")
    Object(s"$expr = $value")
  }

```

which outputs sth like ` mutateDynamicVar : spy_o_8 = tensor([[1.2397, 1.3191]` , the value should be a name rather that it's actual value,how to solve this?

**Comment by shadaj** [comment]
Resolved by #22
